// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOUuERq7KAS8JrV9C4SX2rfo0FwJT7bM',
    appId: '1:1045874524704:android:dda8cc6c47bf9cf3b8b245',
    messagingSenderId: '1045874524704',
    projectId: 'ilan-kibris',
    storageBucket: 'ilan-kibris.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFR0q83lAH-72uhT6I7yVB7E6vJc9Xxs',
    appId: '1:1045874524704:ios:497694d2e74ed5dfb8b245',
    messagingSenderId: '1045874524704',
    projectId: 'ilan-kibris',
    storageBucket: 'ilan-kibris.firebasestorage.app',
    androidClientId: '1045874524704-1dn4sb8allidkerc0f5aob3h64pb43rb.apps.googleusercontent.com',
    iosClientId: '1045874524704-jurfa18fe04ijf05apknpkgdknk9c4ve.apps.googleusercontent.com',
    iosBundleId: 'com.bahasoftware.ilankibris',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_lt49-EY6XFtzunE17dOjDQif9VtmyOE',
    appId: '1:1045874524704:web:69be1d238c67ec5ab8b245',
    messagingSenderId: '1045874524704',
    projectId: 'ilan-kibris',
    authDomain: 'ilan-kibris.firebaseapp.com',
    storageBucket: 'ilan-kibris.firebasestorage.app',
    measurementId: 'G-XZ10P45Z6C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFR0q83lAH-72uhT6I7yVB7E6vJc9Xxs',
    appId: '1:1045874524704:ios:d76c97e9f7f817b7b8b245',
    messagingSenderId: '1045874524704',
    projectId: 'ilan-kibris',
    storageBucket: 'ilan-kibris.firebasestorage.app',
    androidClientId: '1045874524704-1dn4sb8allidkerc0f5aob3h64pb43rb.apps.googleusercontent.com',
    iosClientId: '1045874524704-2a4dmsbuico3c44lms97jromhvd3nrr5.apps.googleusercontent.com',
    iosBundleId: 'com.eclassify.eclassify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_lt49-EY6XFtzunE17dOjDQif9VtmyOE',
    appId: '1:1045874524704:web:69be1d238c67ec5ab8b245',
    messagingSenderId: '1045874524704',
    projectId: 'ilan-kibris',
    authDomain: 'ilan-kibris.firebaseapp.com',
    storageBucket: 'ilan-kibris.firebasestorage.app',
    measurementId: 'G-XZ10P45Z6C',
  );

}